export enum SearchType {
  DATASET = 'GEOGRAPHIC_SEARCH',
  LIST = 'LIST_SEARCH',
  BASELINE = 'BASELINE_SEARCH',
  SBAS = 'SBAS_SEARCH',
  CUSTOM_PRODUCTS = 'ON_DEMAND',
  SARVIEWS_EVENTS = 'EVENT_SEARCH',
  DERIVED_DATASETS = 'DERIVED_DATASETS',
}

export const SearchTypes = Object.keys(SearchType);
