phrase:
  host: https://api.us.app.phrase.com/v2
  project_id: a1f4202162d6aef2fcf9c83d4ff56672
  push:
    sources:
      - file: ./src/assets/i18n/en.json
        params:
          file_format: i18next
          locale_id: en #Can be the name (e.g. en-US)
          tags: REVIEW_NEEDED,ANDY  #List of tags separated by comma to be associated with the new keys contained in the upload.
          update_translations: true #Indicates whether existing translations should be updated with the file content.
  pull:
    targets:
      - file: ./src/assets/i18n/en.json
        params:
          file_format: i18next
          locale_id: en #Can be the name (e.g. en-US)
