version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm set progress=false
      - npm install -g @angular/cli@8.3.21
  pre_build:
    commands:
      - cp src/assets/envs/env-${MATURITY}.js src/assets/env.js
      - npm install --prod
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - cd dist/${APPLICATION}
      - aws s3 sync . "s3://${S3_BUCKET}"
      - cd ../..
      - chmod +x ./invalidate-cf.sh
      - . ./invalidate-cf.sh ${CDN_ID}
