version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm set progress=false
      - npm install -g @angular/cli@15.2.7
  pre_build:
    commands:
      - cp src/app/services/envs/env-${MATURITY}.ts src/app/services/env.ts
      - npm install
      - echo "{\"hash\":\"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}" > src/assets/commit-hash.json
  build:
    commands:
      - ng build --configuration production
  post_build:
    commands:
      - cd dist/${APPLICATION}
      - aws s3 sync . "s3://${S3_BUCKET}"
      - cd ../..
      - chmod +x ./invalidate-cf.sh
      - . ./invalidate-cf.sh ${CDN_ID}
