name: Composite search-ui deploy action

inputs:
  maturity:
    required: true
    type: string
  application:
    required: true
    type: string
  cdn-id:
    required: true
    type: string
  s3-bucket:
    required: true
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: |
        cp src/app/services/envs/env-${{ inputs.maturity }}.ts src/app/services/env.ts
        echo "{\"hash\":\"${{ github.sha }}\"}" > src/assets/commit-hash.json
        npm install -g @angular/cli@17.2.7
        npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: "us-east-1"

    - name: Angular Build
      shell: bash
      run: |
        ng build --configuration production

    - name: Deploy to AWS
      shell: bash
      run: |
        cd dist/${{ inputs.application }}
        aws s3 sync . "s3://${{ inputs.s3-bucket }}"
        aws cloudfront create-invalidation \
            --distribution-id ${{ inputs.cdn-id }} \
            --paths /index.html /manifest.json /ngsw.json /favicon.ico /assets/i18n/* /assets/* /docs/*
