import { BREAKPOINT}  from '@angular/flex-layout';

const SCREEN_BREAKPOINTS_DEFAULT = [
  { alias: 'xs', suffix: 'Xs',
    mediaQuery:	'screen and (max-width: 599px)',
    overlapping: false },
  { alias: 'sm', suffix: 'Sm',
    mediaQuery:	'screen and (min-width: 600px) and (max-width: 959px)',
    overlapping: false },
  { alias: 'md', suffix: 'Md',
    mediaQuery:	'screen and (min-width: 960px) and (max-width: 1279px)',
    overlapping: false },
  { alias: 'lg', suffix: 'Lg',
    mediaQuery:	'screen and (min-width: 1280px) and (max-width: 1919px)',
    overlapping: false },
  { alias: 'xl', suffix: 'Xl',
    mediaQuery:	'screen and (min-width: 1920px) and (max-width: 5000px)',
    overlapping: false },
  { alias: 'lt-sm', suffix: 'LtSm',
    mediaQuery:	'screen and (max-width: 599px)',
    overlapping: false },
  { alias: 'lt-md', suffix: 'LtMd',
    mediaQuery:	'screen and (max-width: 959px)',
    overlapping: false },
  { alias: 'lt-lg', suffix: 'LtLg',
    mediaQuery:	'screen and (max-width: 1279px)',
    overlapping: false },
  { alias: 'lt-xl', suffix: 'LtXl',
    mediaQuery:	'screen and (max-width: 1919px)',
    overlapping: false },
  { alias: 'gt-xs', suffix: 'GtXs',
    mediaQuery:	'screen and (min-width: 600px)',
    overlapping: false },
  { alias: 'gt-sm', suffix: 'GtSm',
    mediaQuery:	'screen and (min-width: 960px)',
    overlapping: false },
  { alias: 'gt-md', suffix: 'GtMd',
    mediaQuery:	'screen and (min-width: 1280px)',
    overlapping: false },
  { alias: 'gt-lg', suffix: 'GtLg',
    mediaQuery:	'screen and (min-width: 1920px)',
    overlapping: false },
];

const SCREEN_BREAKPOINTS = [
  { alias: 'xs', suffix: 'Xs',
    mediaQuery:	'screen and (max-width: 599px)',
    overlapping: false },
  { alias: 'sm', suffix: 'Sm',
    mediaQuery:	'screen and (min-width: 600px) and (max-width: 1139px)',
    overlapping: false },
  { alias: 'md', suffix: 'Md',
    mediaQuery:	'screen and (min-width: 1140px) and (max-width: 1419px)',
    overlapping: false },
  { alias: 'lg', suffix: 'Lg',
    mediaQuery:	'screen and (min-width: 1420px) and (max-width: 1919px)',
    overlapping: false },
  { alias: 'xl', suffix: 'Xl',
    mediaQuery:	'screen and (min-width: 1920px) and (max-width: 5000px)',
    overlapping: false },
  { alias: 'lt-sm', suffix: 'LtSm',
    mediaQuery:	'screen and (max-width: 599px)',
    overlapping: false },
  { alias: 'lt-md', suffix: 'LtMd',
    mediaQuery:	'screen and (max-width: 1139px)',
    overlapping: false },
  { alias: 'lt-lg', suffix: 'LtLg',
    mediaQuery:	'screen and (max-width: 1419px)',
    overlapping: false },
  { alias: 'lt-xl', suffix: 'LtXl',
    mediaQuery:	'screen and (max-width: 1919px)',
    overlapping: false },
  { alias: 'gt-xs', suffix: 'GtXs',
    mediaQuery:	'screen and (min-width: 600px)',
    overlapping: false },
  { alias: 'gt-sm', suffix: 'GtSm',
    mediaQuery:	'screen and (min-width: 1140px)',
    overlapping: false },
  { alias: 'gt-md', suffix: 'GtMd',
    mediaQuery:	'screen and (min-width: 1420px)',
    overlapping: false },
  { alias: 'gt-lg', suffix: 'GtLg',
    mediaQuery:	'screen and (min-width: 1920px)',
    overlapping: false },
];

export const CustomBreakPointsProvider = {
  provide: BREAKPOINT,
  useValue: SCREEN_BREAKPOINTS,
  multi: true
};
