name: Update SearchUI (will)

on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: will
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub_Actions_Role
          aws-region: us-east-1

      - name: build
        uses: ./.github/workflows/search-ui-deploy-composite
        with:
          maturity: test
          application: ${{ vars.APPLICATION }}
          cdn-id: ${{ vars.CDN_ID }}
          s3-bucket: ${{ vars.S3_BUCKET }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
