name: Update SearchUI (will)

on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: will

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/search-ui-deploy-composite
        with:
          maturity: test
          application: ${{ vars.APPLICATION }}
          cdn-id: ${{ vars.CDN_ID }}
          s3-bucket: ${{ vars.S3_BUCKET }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
