name: Deploy andy SearchUI

on:
  push:
    branches:
      - andy/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev-andy
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/search-ui-deploy-composite
        with:
          maturity: ${{ vars.MATURITY }}
          cdn-id: ${{ vars.CDN_ID }}
          s3-bucket: ${{ vars.S3_BUCKET }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
