name: Unit Tests
on:
    push:
    pull_request:
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci
            - name: Run Unit tests
              run: npm run test -- --watch=false
